{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $sh := .Values.sharedHome | default dict -}}
{{- $p := $sh.persistence | default dict -}}
{{- if and (default false $sh.enabled) (default true $p.enabled) (default true $p.create) (not $p.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-shared-home" (include "slurm.fullname" .) }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared-home
spec:
  accessModes:
    {{- toYaml $p.accessModes | nindent 4 }}
  {{- if $p.storageClassName }}
  storageClassName: {{ $p.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $p.size | quote }}
{{- end }}
